### ISSUE TITLE
data split in M3D cap and ITR 

### ISSUE THREAD

**Issue by liu3xing3long** [BAAI-DCAI/M3D#38]
Thanks for the excellent work! 

I have some concerns about the data split in M3D-cap.json file. In all test settings (test/test100/test500/test1k), data are split by file names. However, there exists many files come from the same ct_case/ct_quizze folder with same case ids. 

For eg. 
the 2nd case in test is, 
```json
        {
            "image": "M3D_Cap_npy/ct_quizze/005461/Axial_non_contrast.npy",
            "text": "M3D_Cap_npy/ct_quizze/005461/text.txt"
        },
```      

the corresponding files in train split, as 
```json
        {
            "image": "M3D_Cap_npy/ct_quizze/005461/Coronal_renal_cortical_phase.npy",
            "text": "M3D_Cap_npy/ct_quizze/005461/text.txt"
        },
        {
            "image": "M3D_Cap_npy/ct_quizze/005461/Sagittal_renal_cortical_phase.npy",
            "text": "M3D_Cap_npy/ct_quizze/005461/text.txt"
        },
        {
            "image": "M3D_Cap_npy/ct_quizze/005461/Axial_C__delayed.npy",
            "text": "M3D_Cap_npy/ct_quizze/005461/text.txt"
        },
        {
            "image": "M3D_Cap_npy/ct_quizze/005461/Axial_renal_cortical_phase.npy",
            "text": "M3D_Cap_npy/ct_quizze/005461/text.txt"
        },
```
they both come from the `005461` folder, and although they are constructed from different planes(axial and coronal) or different phases, they actually present the same 3D data acquired at the same time (we usually define them as one Study), as shown in the image:

![image](https://github.com/user-attachments/assets/e53a7d25-d3f1-4784-87f9-bdd9b6593b11)

Many similar files exist in the train/val/test split. I doubt whether this will lead to data leakage between train and val data, since each data from the same folder can be treated augmented images from the very original Study. 

Meanwhile, I suppose this may be the real reason in [issue 22](https://github.com/BAAI-DCAI/M3D/issues/22) ? The model has been overfitted, and the longger you train, the better results you got on the 'train'  split.

I'm really confused about this. Thanks for any reply !

**Comment by baifanxxx** [comment]
Thank you for your concern. As you've observed, the M3D dataset contains multiple CT scans and similar text reports for one patient. When splitting the dataset into training and testing sets, we ensured that image-text pairs do not overlap (i.e., no data leakage), but we did not specifically account for the uniqueness of individual patients. In our setup, while the same patient's different CT scans may appear in both the training and test sets, we believe this is acceptable. If you require a stricter independent data split, you can perform the split at the patient level and provide the corresponding split files.

Regarding issue [[#22](https://github.com/BAAI-DCAI/M3D/issues/22)](https://github.com/BAAI-DCAI/M3D/issues/22), our response clarifies that the problem is unrelated to the dataset split. The reported model performance in the paper was preliminary. The updated performance, which is significantly better, is presented in the latest version of our paper (though not yet updated on arXiv). The improved performance of M3D-CLIP is mainly due to the use of a larger batch size and longer training time, which allowed the model to scale better.

Thank you again for your attention to our work. If you have any further questions, please feel free to contact me.
