### ISSUE TITLE
What is VQA yes or no datasets ?

### ISSUE THREAD

**Issue by zhouhoo** [BAAI-DCAI/M3D#42]
in train.py ,
` vqa_yn_data_train_path: str = field(default=None, metadata={"help": "Path to training VQA Yes or No data."})
  `
could anyone tell me about VQA Yes or No data?  or how to generate it ?the VQA link only shows train/validation/test dataset.

**Comment by baifanxxx** [comment]
Thank you for your question. The VQA-YN dataset refers to a Yes/No question dataset generated using M3D-Cap. Since this dataset hasn't been thoroughly reviewed, I haven't publicly released detailed information about the VQA-YN data, nor have I validated its performance on test tasks. However, if you need it, I can provide you with the VQA-YN dataset [here](https://huggingface.co/datasets/GoodBaiBai88/M3D-VQA/blob/main/M3D_VQA_yn_train.csv).

**Comment by zhouhoo** [comment]
ok,thanks
